/**
 *
 * Import Wallet Page - Constants
 *
 */
// Actions
export const LOAD_WALLET_ADDRESSES =
  'TOMO_WALLET/IMPORT_WALLET/LOAD_WALLET_ADDRESSES';
export const RESET_STATE = 'TOMO_WALLET/IMPORT_WALLET/RESET_STATE';
export const TOGGLE_ADDRESS_POPUP =
  'TOMO_WALLET/IMPORT_WALLET/TOGGLE_ADDRESS_POPUP';
export const UPDATE_CHOSEN_WALLET =
  'TOMO_WALLET/IMPORT_WALLET/UPDATE_CHOSEN_WALLET';
export const UPDATE_ERRORS = 'TOMO_WALLET/IMPORT_WALLET/UPDATE_ERRORS';
export const UPDATE_INPUT = 'TOMO_WALLET/IMPORT_WALLET/UPDATE_INPUT';
export const UPDATE_TYPE = 'TOMO_WALLET/IMPORT_WALLET/UPDATE_TYPE';

// Domain key
export const DOMAIN_KEY = 'importWallet';

// Other constants
export const IMPORT_TYPES = {
  LEDGER: 1,
  RP_OR_PK: 2,
};
