/**
 *
 * Import Wallet Page - Constants
 *
 */
// ===== IMPORTS =====
// Utilities & Constants
import { getMessage } from '../../components/IntlProvider';
import { MSG } from '../../constants';
// ===================

// Actions
export const LOAD_KEYSTORE_FILE =
  'TOMO_WALLET/IMPORT_WALLET/LOAD_KEYSTORE_FILE';
export const LOAD_WALLET_ADDRESSES =
  'TOMO_WALLET/IMPORT_WALLET/LOAD_WALLET_ADDRESSES';
export const RESET_STATE = 'TOMO_WALLET/IMPORT_WALLET/RESET_STATE';
export const REVEAL_PASSWORD_INPUT =
  'TOMO_WALLET/IMPORT_WALLET/REVEAL_PASSWORD_INPUT';
export const TOGGLE_ADDRESS_POPUP =
  'TOMO_WALLET/IMPORT_WALLET/TOGGLE_ADDRESS_POPUP';
export const TOGGLE_PASSWORD_POPUP =
  'TOMO_WALLET/IMPORT_WALLET/TOGGLE_PASSWORD_POPUP';
export const UPDATE_CHOSEN_WALLET =
  'TOMO_WALLET/IMPORT_WALLET/UPDATE_CHOSEN_WALLET';
export const UPDATE_ERRORS = 'TOMO_WALLET/IMPORT_WALLET/UPDATE_ERRORS';
export const UPDATE_KEY_INPUT_TYPE =
  'TOMO_WALLET/IMPORT_WALLET/UPDATE_KEY_INPUT_TYPE';
export const UPDATE_INPUT = 'TOMO_WALLET/IMPORT_WALLET/UPDATE_INPUT';
export const UPDATE_PASSWORD_POPUP_ERRORS =
  'TOMO_WALLET/IMPORT_WALLET/UPDATE_PASSWORD_POPUP_ERRORS';
export const UPDATE_PASSWORD_POPUP_INPUT =
  'TOMO_WALLET/IMPORT_WALLET/UPDATE_PASSWORD_POPUP_INPUT';
export const UPDATE_TYPE = 'TOMO_WALLET/IMPORT_WALLET/UPDATE_TYPE';

// Domain key
export const DOMAIN_KEY = 'importWallet';

// Other constants
export const IMPORT_TYPES = {
  LEDGER: 1,
  META_MASK: 2,
  RP_OR_PK: 3,
  KEYSTORE: 4,
};
export const KEY_INPUT_TYPE = {
  PRIVATE_KEY: 1,
  RECOVERY_PHRASE: 2,
};
export const KEY_INPUT_OPTIONS = [
  {
    label: getMessage(MSG.IMPORT_WALLET_TAB_RECOVERY_PHRASE_TYPE_PRIVATE_KEY),
    value: 1,
  },
  {
    label: getMessage(MSG.IMPORT_WALLET_TAB_RECOVERY_PHRASE_TYPE_MNEMONIC),
    value: 2,
  },
];
