sudo: required
language: node_js
node_js: "10"

jobs:
  include:
    - stage: Test
      script: npm run test

    - stage: Release
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        overwrite: true
        on:
          tags: true

stages:
  - name: Test
  - name: Release Application
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tomochain/tomowallet-web
