/**
 *
 * TomoWallet - Welcome Page - Constants
 *
 */
// Actions
export const LOAD_KEYSTORE_DATA = 'TOMOWALLET/WELCOME/LOAD_KEYSTORE_DATA';
export const RESET_STATE = 'TOMOWALLET/WELCOME/RESET_STATE';
export const TOGGLE_PASSWORD_FORM = 'TOMOWALLET/WELCOME/TOGGLE_PASSWORD_FORM';
export const UPDATE_PASSWORD_ERRORS =
  'TOMOWALLET/WELCOME/UPDATE_PASSWORD_ERRORS';
export const UPDATE_PASSWORD_INPUT = 'TOMOWALLET/WELCOME/UPDATE_PASSWORD_INPUT';

// Domain key
export const DOMAIN_KEY = 'welcome';
