import injectReducer from './injectReducer';
import injectSaga from './injectSaga';
import history from './history';
import createDeepEqualSelector from './deepSelector';
import {
  changeInputWithSubmit,
  convertLocaleNumber,
  copyToClipboard,
  detectSubmit,
  downloadFile,
  removeTrailingZero,
  shuffleArray,
  trimMnemonic,
} from './miscellaneous';
import {
  bnToDecimals,
  convertAmountWithDecimals,
  decimalsToBN,
  decryptKeystore,
  encryptKeystore,
  estimateCurrencyFee,
  estimateTRC20Fee,
  estimateTRC21Fee,
  fromWei,
  generateWeb3,
  getBalance,
  getLedgerTokenTransferData,
  getWalletInfo,
  isAddress,
  isPrivateKey,
  isRecoveryPhrase,
  mnemonicToPrivateKey,
  repeatGetTransaction,
  sendMoney,
  sendToken,
} from './blockchain';
import getValidations, { mergeErrors } from './validations';
import { withGlobal } from './injectGlobal';
import {
  getLedger,
  getLocale,
  getNetwork,
  getWeb3Info,
  removeLedger,
  removeLocale,
  removeNetwork,
  removeWeb3Info,
  setLedger,
  setNetwork,
  setLocale,
  setWeb3Info,
} from './storage';
import electron, {
  detectKeystore,
  isElectron,
  readKeystore,
  removeKeystore,
  writeKeystore,
} from './electron';

export {
  bnToDecimals,
  changeInputWithSubmit,
  convertLocaleNumber,
  convertAmountWithDecimals,
  copyToClipboard,
  createDeepEqualSelector,
  decimalsToBN,
  decryptKeystore,
  detectKeystore,
  detectSubmit,
  downloadFile,
  electron,
  encryptKeystore,
  estimateCurrencyFee,
  estimateTRC20Fee,
  estimateTRC21Fee,
  fromWei,
  generateWeb3,
  getBalance,
  getLedger,
  getLedgerTokenTransferData,
  getLocale,
  getNetwork,
  getValidations,
  getWalletInfo,
  getWeb3Info,
  history,
  injectReducer,
  injectSaga,
  isAddress,
  isElectron,
  isPrivateKey,
  isRecoveryPhrase,
  mergeErrors,
  mnemonicToPrivateKey,
  readKeystore,
  removeKeystore,
  removeLedger,
  removeLocale,
  removeNetwork,
  removeTrailingZero,
  removeWeb3Info,
  repeatGetTransaction,
  sendMoney,
  sendToken,
  setLedger,
  setLocale,
  setNetwork,
  setWeb3Info,
  shuffleArray,
  trimMnemonic,
  withGlobal,
  writeKeystore,
};
