export const STORE_WALLET_INFO = 'TOMO_WALLET/GLOBAL/STORE_WALLET_INFO';
export const RELEASE_WALLET_INFO = 'TOMO_WALLET/GLOBAL/RELEASE_WALLET_INFO';
export const SET_LANGUAGE = 'TOMO_WALLET/GLOBAL/SET_LANGUAGE';
