export const STORE_ACCOUNT_INFO = 'TOMO_WALLET/GLOBAL/STORE_ACCOUNT_INFO';
export const RELEASE_ACCOUNT_INFO = 'TOMO_WALLET/GLOBAL/RELEASE_ACCOUNT_INFO';
export const SET_LANGUAGE = 'TOMO_WALLET/GLOBAL/SET_LANGUAGE';
export const RESET_GLOBAL_STATE = 'TOMO_WALLET/GLOBAL/RESET_GLOBAL_STATE';
