/**
 *
 * TomoWallet - Global Constants
 *
 */
// Actions
export const RELEASE_WALLET_INFO = 'TOMO_WALLET/GLOBAL/RELEASE_WALLET_INFO';
export const RESET_WALLET_POPUP = 'TOMO_WALLET/GLOBAL/RESET_WALLET_POPUP';
export const SET_LANGUAGE = 'TOMO_WALLET/GLOBAL/SET_LANGUAGE';
export const SET_NETWORK = 'TOMO_WALLET/GLOBAL/SET_NETWORK';
export const STORE_WALLET_INFO = 'TOMO_WALLET/GLOBAL/STORE_WALLET_INFO';
export const TOGGLE_LOADING_SCREEN = 'TOMO_WALLET/GLOBAL/TOGGLE_LOADING_SCREEN';
export const TOGGLE_NETWORK_CONFIRMATION_POPUP =
  'TOMO_WALLET/GLOBAL/TOGGLE_NETWORK_CONFIRMATION_POPUP';
export const TOGGLE_NETWORK_DROPDOWN =
  'TOMO_WALLET/GLOBAL/TOGGLE_NETWORK_DROPDOWN';
export const TOGGLE_WALLET_POPUP = 'TOMO_WALLET/GLOBAL/TOGGLE_WALLET_POPUP';
export const UPDATE_WALLET_POPUP_CONTENT_TAB =
  'TOMO_WALLET/GLOBAL/UPDATE_WALLET_POPUP_CONTENT_TAB';
export const UPDATE_WALLET_POPUP_STAGE =
  'TOMO_WALLET/GLOBAL/UPDATE_WALLET_POPUP_STAGE';

// Others
export const WALLET_POPUP_STAGE = {
  WARNING: 1,
  CONTENT: 2,
};
export const WALLET_POPUP_CONTENT_TAB = {
  RECOVERY_PHRASE: 1,
  PRIVATE_KEY: 2,
};
