export const GENERATE_MNEMONIC =
  'TOMO_WALLET/RECOVERY_PHRASE/GENERATE_MNEMONIC';
export const ADD_MNEMONIC_WORD =
  'TOMO_WALLET/RECOVERY_PHRASE/ADD_MNEMONIC_WORD';
export const REMOVE_MNEMONIC_WORD =
  'TOMO_WALLET/RECOVERY_PHRASE/REMOVE_MNEMONIC_WORD';
export const VERIFY_MNEMONIC = 'TOMO_WALLET/RECOVERY_PHRASE/VERIFY_MNEMONIC';
export const UPDATE_FORM_STATE =
  'TOMO_WALLET/RECOVERY_PHRASE/UPDATE_FORM_STATE';
export const RESET_STATE = 'TOMO_WALLET/RECOVERY_PHRASE/RESET_STATE';
export const TOGGLE_CONFIRMATION_POPUP =
  'TOMO_WALLET/RECOVERY_PHRASE/TOGGLE_CONFIRMATION_POPUP';
export const TOGGLE_VERIFYCATION_POPUP =
  'TOMO_WALLET/RECOVERY_PHRASE/TOGGLE_VERIFYCATION_POPUP';
export const TOGGLE_SUCCESS_POPUP =
  'TOMO_WALLET/RECOVERY_PHRASE/TOGGLE_SUCCESS_POPUP';

export const DOMAIN_KEY = 'recoveryPhrase';

export const FORM_STATES = {
  WARNING: 1,
  PHRASE: 2,
};
